### ISSUE TITLE
Not working for ISO files

### ISSUE THREAD

**Issue by Saman24** [zoffline/BDInfoCLI-ng#1]
Hello

BDInfo.exe -w C:\Users\Administrator\Desktop\Storm.Boy.2019.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam\ C:\Users\Administrator\Desktop\report
Please wait while we scan the disc...
Preparing to analyze the following:

                File           Elapsed      Remaining

Scan completed successfully.
Please wait while we generate the report...
Object reference not set to an instance of an object.

Windows Server 2008
BDInfoCLI : Version : 0.7.3.65534

**Comment by zoffline** [comment]
You're passing the folder the ISO file is in as the first argument, you need to pass the whole ISO file path.

I'll add a check ensure that either a directory containing a BDMV folder or an iso file is passed and give a proper error message if not.

**Comment by Saman24** [comment]
Thank you for reply. I was waiting for you!
Can you give me an example? do you mean like this? "BDInfo.exe -w C:\Users\Administrator\Desktop\Storm.Boy.2019.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam\ Storm.Boy.2019.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam.iso" ?
 because it says it does not exist or is not a directory

**Comment by Saman24** [comment]
I'm sure the iso file path is correct, I don't know why is says it does not exist??
I even change the filename to a shorter name but still same error?

**Comment by zoffline** [comment]
Yes, but there's a space between "MTeam\ Storm.Boy" that very likely shouldn't be there making the path wrong. If that's not the problem, I'll download that ISO and test it.

**Comment by Saman24** [comment]
The space in here is a typo, its not on the path. Also I put my path inside " "
anyway I tested another ISO file : 
C:\Users\Administrator\Desktop\Apollo.11.2019.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam\Apollo.11.2019.BluRay.1080p.AVC.DTS-HD.MA5.1-MTeam.iso does not exist or is not a directory

Can you please take a look into this issue ?
 I'm using .NET Framework 4.7 , Windows server 2008
Thank you

**Comment by zoffline** [comment]
Ah, you're using the prebuilt which I made prior to supporting ISO files. I hadn't updated it for awhile due to a build issue, but the issue's resolved now and I've updated the prebuilt with the latest version. Please try again using this latest version: https://raw.githubusercontent.com/zoffline/BDInfoCLI-ng/UHD_Support_CLI/prebuilt/BDInfoCLI-ng_v0.7.5.5.zip

**Comment by Saman24** [comment]
Working perfectly now. Thank you very much
