### ISSUE TITLE
Descending order of the movie's playlist  according to the size in linux

### ISSUE THREAD

**Issue by alitteration** [zoffline/BDInfoCLI-ng#4]
Is it possible to get the script to show the playlist in descending order?

**Comment by zoffline** [comment]
By descending size as opposed to by descending playlist length as it should already be doing? Or are you not seeing the list in descending length even?

e.g. random blu-ray I have on hand descends by playlist length:
```Please wait while we scan the disc...
#   Group  Playlist File  Length    Estimated Bytes Measured Bytes

1   1      00015.MPLS     04:44:00  38,130,960,384  -
2   1      00003.MPLS     00:22:10  2,985,682,944   -
3   1      00010.MPLS     00:22:10  2,971,140,096   -
4   1      00008.MPLS     00:22:08  2,976,602,112   -
5   1      00009.MPLS     00:22:08  2,973,763,584   -
6   1      00007.MPLS     00:22:08  2,972,160,000   -
7   1      00004.MPLS     00:22:04  2,965,493,760   -
8   1      00006.MPLS     00:22:00  2,958,544,896   -
9   1      00000.MPLS     00:21:43  2,914,025,472   -
10  1      00002.MPLS     00:21:41  2,906,578,944   -
11  1      00011.MPLS     00:21:34  2,897,928,192   -
12  1      00005.MPLS     00:21:32  2,893,449,216   -
13  1      00001.MPLS     00:21:20  2,855,725,056   -
14  1      00012.MPLS     00:21:18  2,859,866,112   -
15  2      00014.MPLS     00:00:34  48,912,384      -```

**Comment by alitteration** [comment]
Hello,
Something like that : 

#   Group  Playlist File  Length    Estimated Bytes Measured Bytes

1   1      00801.MPLS     01:52:26  16,520,939,520  -
2   2      00800.MPLS     01:47:09  28,239,034,368  -
3   3      00203.MPLS     00:12:22  912,961,536     -

I would like the highest bitrate to be on the top of them all, is this possible ?

**Comment by zoffline** [comment]
It's very rare that the largest playlist isn't also the longest, which is how they're sorted already so I'm not inclined to add an additional option for it, sorry.
