### ISSUE TITLE
How would one run the program

### ISSUE THREAD

**Issue by Motophan** [zoffline/BDInfoCLI-ng#5]
The docker container exits immediatally after opening. 

I cant figure out what I am suppose to do to run it

**Comment by zoffline** [comment]
Are you using Windows, Linux, or Mac? If using Linux or Mac, I'd recommend using the Docker container via this script: https://github.com/zoffline/BDInfoCLI-ng/blob/UHD_Support_CLI/scripts/bdinfo
If using Windows I'd recommend forgoing Docker and use the prebuilt exe directly.
